#!/usr/bin/env bash
# Takes in a domain name and sub domain names to output their
# sub domain, record type, and destination

if [ $# -eq 2 ]
    then
    echo -n "The subdomain $2 "
    dig $2.$1 | grep -A1 "ANSWER SECTION" | tail -1 | awk '{print "is a", $4, "record and points to", $5}'
else
    for i in www lb-01 web-01 web-02;
    do
	echo -n "The subdomain $i "
	dig $i.$1 | grep -A1 "ANSWER SECTION" | tail -1 | awk '{print "is a", $4, "record and points to", $5}'
	done
fi
