#!/usr/bin/env bash
# Configures Nginx server with custom header

# Update, Upgrade, and installs nginx for new server
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

# initial configuration setting for nginx changing listening port to 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

# Adds custom http response header
C_Header="\\\n\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "15i $C_Header" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
