#!/usr/bin/env bash
# Installs HAProxy 1.8 (stable LTS) on server and configures it

# Install 'add-apt-repository' functionality 
sudo apt-get install software-properties-common

# Download, update, upgrade, and install HAProxy 1.8
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

# Download and place configuration file
https://raw.githubusercontent.com/jsjimenez51/holberton-system_engineering-devops/master/0x0F-load_balancer/HAP_Config1.cfg
sudo mv haproxy.cfg /etc/haproxy
sudo service haproxy restart
