#!/usr/bin/env bash
# Fixes the web server by fixing the symblink between
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
