#!/usr/bin/env bash
# Re-configures a Nginx server to listen on port 80

FILE=/etc/nginx/sites-enabled/default
OLDPORT='8080 default_server'
NEWPORT='80 default_server'

sudo sed -i "s/$OLDPORT/$NEWPORT/" $FILE

sudo service nginx restart
