#!/usr/bin/env bash
# Script to display "Holberton School" 10 times
ct=1
while [ $ct -le 10 ]
do
	if [[ $ct -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $ct -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	ct=$((ct + 1))
done
