#!/usr/bin/env bash
# transfers a file from client to server
# $1: the path to the file being transferred
# $2: the ip address of the server file is being transferred to
# $3: the username that connects with scp
# $4: the path to the ssh private key that scp uses

if [ "$#" -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
