#!/usr/bin/env bash
# Installs and configures Nginx to server

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
