#!/usr/bin/env bash
# configures nginx user to be nginx listening on all ips on 8080

# stop current service of Apache2 which listens on port 8080
sudo pkill -f apache2

# set user nginx permission
sudo chmod 744 /etc/nginx/nginx.conf

# change ownership of nginx.conf from root to nginx
sudo chown -R nginx:nginx /etc/nginx/nginx.conf

# configure nginx to listen to port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

sudo -u nginx bash -c 'service nginx restart'
