#!/usr/bin/env bash
# configures nginx user to be nginx listening on all ips on 8080
kill "$(netstat -lptn | grep :8080 | awk '{print $NF}' | cut -d'/' -f1)"
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
